
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView Editor;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView cODE;

	private global::Gtk.HBox hbox3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label KernelSizeString;

	private global::Gtk.SpinButton KernelSize;

	private global::Gtk.Button ResizeKernelButton;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Notebook notebook5;

	private global::Gtk.Fixed fixed5;

	private global::Gtk.Entry entry4;

	private global::Gtk.Label label16;

	private global::Gtk.Label label15;

	private global::Gtk.Button Compile;

	private global::Gtk.Button Run;

	private global::Gtk.Label label14;

	private global::Gtk.Fixed fixed6;

	private global::Gtk.Button button13;

	private global::Gtk.Button button14;

	private global::Gtk.Button button15;

	private global::Gtk.Button button1;

	private global::Gtk.Button GrabRam;

	private global::Gtk.Label label17;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView Cons;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry CommandToSend;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow Result;

	private global::Gtk.TextView ResultText;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Strobe Debugger");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1000;
		this.DefaultHeight = 700;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Editor = new global::Gtk.TextView();
		this.Editor.CanFocus = true;
		this.Editor.Name = "Editor";
		this.GtkScrolledWindow.Add(this.Editor);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w3.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.cODE = new global::Gtk.TextView();
		this.cODE.CanFocus = true;
		this.cODE.Name = "cODE";
		this.cODE.Editable = false;
		this.cODE.CursorVisible = false;
		this.cODE.AcceptsTab = false;
		this.GtkScrolledWindow1.Add(this.cODE);
		this.vbox1.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow1]));
		w5.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.KernelSizeString = new global::Gtk.Label();
		this.KernelSizeString.Name = "KernelSizeString";
		this.KernelSizeString.LabelProp = global::Mono.Unix.Catalog.GetString("Memory Size");
		this.vbox4.Add(this.KernelSizeString);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.KernelSizeString]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(5));
		// Container child vbox4.Gtk.Box+BoxChild
		this.KernelSize = new global::Gtk.SpinButton(0, 2147483647, 1);
		this.KernelSize.CanFocus = true;
		this.KernelSize.Name = "KernelSize";
		this.KernelSize.Adjustment.PageIncrement = 10;
		this.KernelSize.ClimbRate = 1;
		this.KernelSize.Numeric = true;
		this.KernelSize.Value = 1048576;
		this.vbox4.Add(this.KernelSize);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.KernelSize]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.ResizeKernelButton = new global::Gtk.Button();
		this.ResizeKernelButton.CanFocus = true;
		this.ResizeKernelButton.Name = "ResizeKernelButton";
		this.ResizeKernelButton.UseUnderline = true;
		this.ResizeKernelButton.Label = global::Mono.Unix.Catalog.GetString("Reload");
		this.vbox4.Add(this.ResizeKernelButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.ResizeKernelButton]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox3.Add(this.vbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.notebook5 = new global::Gtk.Notebook();
		this.notebook5.CanFocus = true;
		this.notebook5.Name = "notebook5";
		this.notebook5.CurrentPage = 1;
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.fixed5 = new global::Gtk.Fixed();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = false;
		this.entry4.InvisibleChar = '●';
		this.fixed5.Add(this.entry4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry4]));
		w10.X = 9;
		w10.Y = 35;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Command Line Arguments");
		this.fixed5.Add(this.label16);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label16]));
		w11.X = 4;
		w11.Y = 12;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Application");
		this.fixed5.Add(this.label15);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label15]));
		w12.X = 204;
		w12.Y = 12;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.Compile = new global::Gtk.Button();
		this.Compile.CanFocus = true;
		this.Compile.Name = "Compile";
		this.Compile.UseUnderline = true;
		this.Compile.Label = global::Mono.Unix.Catalog.GetString("Compile");
		this.fixed5.Add(this.Compile);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.Compile]));
		w13.X = 181;
		w13.Y = 35;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.Run = new global::Gtk.Button();
		this.Run.CanFocus = true;
		this.Run.Name = "Run";
		this.Run.UseUnderline = true;
		this.Run.Label = global::Mono.Unix.Catalog.GetString("Run");
		this.fixed5.Add(this.Run);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.Run]));
		w14.X = 255;
		w14.Y = 35;
		this.notebook5.Add(this.fixed5);
		// Notebook tab
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Runtime");
		this.notebook5.SetTabLabel(this.fixed5, this.label14);
		this.label14.ShowAll();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.fixed6 = new global::Gtk.Fixed();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("Step Once");
		this.fixed6.Add(this.button13);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.button13]));
		w16.X = 8;
		w16.Y = 10;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.button14 = new global::Gtk.Button();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString("Until Error");
		this.fixed6.Add(this.button14);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.button14]));
		w17.X = 90;
		w17.Y = 10;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("Until End");
		this.fixed6.Add(this.button15);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.button15]));
		w18.X = 170;
		w18.Y = 10;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.fixed6.Add(this.button1);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.button1]));
		w19.X = 241;
		w19.Y = 10;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.GrabRam = new global::Gtk.Button();
		this.GrabRam.CanFocus = true;
		this.GrabRam.Name = "GrabRam";
		this.GrabRam.UseUnderline = true;
		this.GrabRam.Label = global::Mono.Unix.Catalog.GetString("Dump Memory");
		this.fixed6.Add(this.GrabRam);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.GrabRam]));
		w20.X = 284;
		w20.Y = 10;
		this.notebook5.Add(this.fixed6);
		global::Gtk.Notebook.NotebookChild w21 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5[this.fixed6]));
		w21.Position = 1;
		// Notebook tab
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Debugger");
		this.notebook5.SetTabLabel(this.fixed6, this.label17);
		this.label17.ShowAll();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.Cons = new global::Gtk.TextView();
		this.Cons.CanFocus = true;
		this.Cons.Name = "Cons";
		this.Cons.Editable = false;
		this.Cons.CursorVisible = false;
		this.GtkScrolledWindow2.Add(this.Cons);
		this.vbox2.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow2]));
		w23.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.CommandToSend = new global::Gtk.Entry();
		this.CommandToSend.CanFocus = true;
		this.CommandToSend.Name = "CommandToSend";
		this.CommandToSend.IsEditable = true;
		this.CommandToSend.InvisibleChar = '●';
		this.hbox1.Add(this.CommandToSend);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.CommandToSend]));
		w24.Position = 0;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.notebook5.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5[this.vbox2]));
		w26.Position = 2;
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Console");
		this.notebook5.SetTabLabel(this.vbox2, this.label1);
		this.label1.ShowAll();
		this.hbox4.Add(this.notebook5);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.notebook5]));
		w27.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Result = new global::Gtk.ScrolledWindow();
		this.Result.Name = "Result";
		this.Result.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child Result.Gtk.Container+ContainerChild
		this.ResultText = new global::Gtk.TextView();
		this.ResultText.CanFocus = true;
		this.ResultText.Name = "ResultText";
		this.ResultText.Editable = false;
		this.Result.Add(this.ResultText);
		this.hbox4.Add(this.Result);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Result]));
		w29.Position = 1;
		this.hbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
		w30.Position = 1;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ResizeKernelButton.Clicked += new global::System.EventHandler(this.OnResizeKernelButtonClicked);
		this.Compile.Clicked += new global::System.EventHandler(this.OnCompileClicked);
		this.Run.Clicked += new global::System.EventHandler(this.OnRunClicked);
		this.button13.Clicked += new global::System.EventHandler(this.StepOnce);
		this.button14.Clicked += new global::System.EventHandler(this.UntilError);
		this.button15.Clicked += new global::System.EventHandler(this.UntilEnd);
		this.button1.Clicked += new global::System.EventHandler(this.StopKernel);
		this.GrabRam.Clicked += new global::System.EventHandler(this.DumMem);
	}
}
